### ISSUE TITLE
0.16.26 : Error during build with API

### ISSUE THREAD

**Issue by davinkevin** [jspm/jspm-cli#1493]
Since the release of 0.16.26, the build defined here (https://github.com/davinkevin/Podcast-Server/blob/master/gulp/tasks/build.js#L28) stop working with the following error : 

```
TypeError: Incorrect configuration order. The baseURL must be configured with the first SystemJS.config call.
    at SystemJSNodeLoader.SystemJSLoader.config (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1772:13)
    at SystemJSNodeLoader.loader.config (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:154:18)
    at Builder.config (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:315:15)
    at new Builder (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:48:10)
    at Builder (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/jspm/lib/bundle.js:30:19)
    at Gulp.<anonymous> (/Users/kevin/Workspace/IntelliJ/Podcast Server/gulp/tasks/build.js:28:9)
    at module.exports (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/run-sequence/index.js:88:16)
    at Gulp.onTaskEnd (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/run-sequence/index.js:77:5)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kevin/Workspace/IntelliJ/Podcast Server/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
```

The travis build/log with this problem : https://travis-ci.org/davinkevin/Podcast-Server/builds/106392120

I don't think something I used is now deprecated, so I don't understand why it stop working.

Waiting for help, I've modified the version in the package.json to be only on the 0.16.25.
Thanks for your help.

**Comment by guybedford** [comment]
Thanks, this was a SystemJS error due to the Array polyfill for flatMap. Fixed in https://github.com/systemjs/systemjs/commit/75008f8ff6a8798cc958f53ef6705ebf7c8cc805 pending SystemJS release.

**Comment by mikebridge** [comment]
I still have this error with 0.16.29 but I can't figure out what's causing it.  

```javascript
<script src='/assets/jspm_packages/system.js'></script>
<script src='/assets/config.js'></script>
<!-- ... -->
<script>
    System.config({
        baseURL: '/assets/javascripts'
    });
</script>
```

It looks like I have your [patch](https://github.com/systemjs/systemjs/commit/75008f8ff6a8798cc958f53ef6705ebf7c8cc805) locally. Do you know what else I should be looking for?
