### ISSUE TITLE
Aurelia Skeleton with JSPM 0.17 problem

### ISSUE THREAD

**Issue by MrChriZ** [jspm/jspm-cli#2230]
I'm trying to get started with Aurelia and the JSPM 0.17 Beta.
I'm starting with the Aurelia skeleton available here:
https://github.com/aurelia/skeleton-navigation
Using the skeleton-typescript skeleton in particular and then updating JSPM to the latest 0,17 Beta.

Whilst everything appears to build fine I'm having a problem with bundling.
When I perform gulp bundle the following error comes up:
 Error: ENOENT: no such file or directory, open 'Z:\aureliaskeleton\jspm_packages\github\twbs\bootstrap
@3.3.7\js\bootstrap.js'

If I don't update to the JSPM Beta then the issue does not come up.
Is there anything I might be missing?

Interestingly I found this on the Aurelia issues area:
https://github.com/aurelia/skeleton-navigation/issues/653

However, the solutions there don't seem to work with 0.17.

Thanks,
Chris.

**Comment by guybedford** [comment]
This should be working now if you uninstall then reinstall bootstrap.

//cc @AshleyGrant for some reason I needed to update your override from August here - https://github.com/jspm/registry/commit/7526a9bb3332054523c1fb908923f3562d911151.

**Comment by MrChriZ** [comment]
Thanks Guy.  I've tried uninstalling and reinstalling but it's not picked that update up.
Does it cache the registry or something?

**Comment by MrChriZ** [comment]
I tried jspm cc and jspm install -f but still no go.
So I've manually updated the bootstrap@3.3.7.json file in jspm_packages\github\twbs
That seems to have got me past one error and on to another:
Error on fetch for github:twbs/bootstrap@3.3.7/css/bootstrap.css!github:systemjs/plugin-text@0.0.8/text.js

**Comment by MrChriZ** [comment]
I've got past that issue by updating line 31 of bundle.js too "bootstrap/dist/css/bootstrap.css!text",
I'm not sure why that happens with JSPM 0.17 and not 0.16
I've now ran into
Error on dependency parsing for npm:jquery@2.2.4/src/intro.js at file:Z:/skeleton/jspm_packages/npm/jquery@2.2.4/src/intro.js
        MultipleErrors: <compiler-parse-input>:45:1: Unexpected token End of File
<compiler-parse-input>:45:1: Unexpected token End of File
<compiler-parse-input>:45:1: Unexpected token End of File
