### ISSUE TITLE
jspm init error at node v8.0.0 npm 5.0.0

### ISSUE THREAD

**Issue by LearnShare** [jspm/jspm-cli#2300]
jspm init

```
ok   Verified package.json at package.json
     Verified config file at jspm.config.js
     Looking up loader files...

warn Error on lookup for github:systemjs/systemjs
     TypeError: "timeout" must be an unsigned integer
         at validateTimeout (child_process.js:620:11)
         at Object.exports.execFile (child_process.js:183:3)
         at exports.exec (child_process.js:138:18)
         at module.exports (/Users/hu/works/redux-test/node_modules/jspm-github/exec-git.js:64:5)
         at /Users/hu/works/redux-test/node_modules/jspm-github/github.js:382:7
         at initializePromise (/Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:589:5)
         at new Promise$1 (/Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:1077:33)
         at GithubLocation.lookup (/Users/hu/works/redux-test/node_modules/jspm-github/github.js:381:12)
         at /Users/hu/works/redux-test/node_modules/jspm/lib/registry.js:117:30
         at tryCatch (/Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:539:12)
         at invokeCallback (/Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:554:13)
         at /Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:629:16
         at flush (/Users/hu/works/redux-test/node_modules/rsvp/dist/rsvp.js:2414:5)
         at _combinedTickCallback (internal/process/next_tick.js:95:7)
         at process._tickCallback (internal/process/next_tick.js:161:9)

err

err  Error downloading loader files.

err
```

```
node v8.0.0
npm 5.0.0
jspm@0.16.53
```

update: works at node v7.10.0 (npm v4.2.0)

**Comment by ajimix** [comment]
Same problem here with node 8 and npm 5

**Comment by ajimix** [comment]
0.17 beta 41 works fine with node 8 and npm 5

**Comment by guybedford** [comment]
I've published a 0.13.18 of jspm-github with the fix here. This is on the upgrade path for the current 0.16, so should work with an uninstall and reinstall of jspm 0.16.

**Comment by RomkeVdMeulen** [comment]
Still seeing this with 0.16.53, even after uninstall and reinstall.

**Comment by guybedford** [comment]
Ensure that `npm ls jspm-github` is showing version 0.13.18 of jspm-github.

**Comment by RomkeVdMeulen** [comment]
My mistake: I reinstalled with Node 6. Reinstalling with Node 8 works.
