### ISSUE TITLE
An instance where npm install works and jspm install npm: doesnt

### ISSUE THREAD

**Issue by reggi** [jspm/jspm-cli#363]
For some reason `jspm install npm:masonry-layout` throws this error

```
No version match found for npm:get-size@~1.2.4
```

and npm works with

```
npm install masonry-layout
```

Perhaps a versioning related bug?

Masonry does have a [weird version requirement for get-size](https://github.com/desandro/masonry/blob/master/package.json#L7), however NPM parses it fine. 

Masonry's dependancy for get-size is this:

```
"get-size": ">=1.1.4 <1.3"
```

I don't know why JSPM is looking for 1.2.4 when the latest version is 1.2.2.

**Comment by guybedford** [comment]
Thanks, I've fixed in https://github.com/jspm/npm/commit/cfead5aa7dbd47504a7ad3c08d6e5e4231626469.

**Comment by reggi** [comment]
@guybedford Wow, I'm glad this was helpful! Thanks!

**Comment by reggi** [comment]
I've adopted these changes into my global version of `jspm` using this command

```
cd `$(which jspm) | sed 's/jspm//' | awk '{print $1"../../node_modules/jspm"}'` && npm install http://github.com/jspm/npm/tarball/master
```

I'm still getting the error.

**Comment by reggi** [comment]
Even in the test get-size is resolving to `1.2.0` were npm is resolving to `get-size@1.2.2` which is odd.

**Comment by guybedford** [comment]
@reggi there must be something up with your update script here. You need to replace the `jspm-npm` package within the node_modules folder of your global jspm install.

**Comment by reggi** [comment]
I looked inside `npm.js` and saw the changes and also put a simple `console.log` at the top of `npm.js` and when I ran `jspm` it outputted. I'll try it again.

**Comment by reggi** [comment]
In my script above I was installing the unpublished version of `jspm-npm` again. I'm looking into something with.

```
rm -rf jspm-npm && git clone https://github.com/jspm/npm jspm-npm && cd jspm-npm/ && npm install
```

**Comment by guybedford** [comment]
Oh right, note that when you do custom changes to npm, it doesn't know to clear the cache.

This can be done with `jspm install npm:masonry-layout -f` which acts to clear the cache down the install tree for that install.

**Comment by reggi** [comment]
Worked! It as really satisfying seeing it finally download.

**Comment by guybedford** [comment]
This is now released on jspm@0.10.4.
