### ISSUE TITLE
err  Unable to load endpoint army-knife@npm

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#456]
I keep tripping up on this. It's just not intuitive to me, and really hard to work with. Basically, I have this override in my project:

```js
  "jspm": {
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
    "dependencies": {
      "army-knife": "npm:army-knife@^0.1.0",
      "async": "npm:async@^0.9.0",
      "big": "github:MikeMcl/big.js@^2.5.1",
      "bignumber": "github:MikeMcl/bignumber.js@^1.4.1",
      "bootstrap": "^3.2.0",
      "bootstrap-datepicker": "github:eternicode/bootstrap-datepicker@^1.3.0",
      "famous": "github:trusktr/famous@jspm",
      "infamous": "npm:infamous@0.0.34",
      "james-bond": "npm:james-bond@^0.0.0",
      "jquery": "^2.1.1",
      "jquery-tooltipster": "github:iamceege/tooltipster@^3.2.6",
      "jsfromhell": "github:jonasraoni/JSFromHell@master",
      "jss": "npm:jss@^0.10.1",
      "jss-nested": "npm:jss-nested@^0.1.4",
      "leaflet": "github:RickMohr/Leaflet@better-inertial-scrolling",
      "operative": "npm:operative@^0.3.2",
      "string": "npm:string@^3.0.0"
    }
  }
```

I think it has something to do with registry being set to jspm, and trying to get npm packages?

And then I set my override to this:

```js
{
  "jspm": {
    "registry": "npm",
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
    "dependencies": {
      "army-knife": "^0.1.0",
      "async": "^0.9.0",
      "big": "github:MikeMcl/big.js@^2.5.1",
      "bignumber": "github:MikeMcl/bignumber.js@^1.4.1",
      "bootstrap": "^3.2.0",
      "bootstrap-datepicker": "github:eternicode/bootstrap-datepicker@^1.3.0",
      "famous": "github:trusktr/famous@jspm",
      "infamous": "0.0.34",
      "james-bond": "^0.0.0",
      "jquery": "^2.1.1",
      "jquery-tooltipster": "github:iamceege/tooltipster@^3.2.6",
      "jsfromhell": "github:jonasraoni/JSFromHell@master",
      "jss": "^0.10.1",
      "jss-nested": "^0.1.4",
      "leaflet": "github:RickMohr/Leaflet@better-inertial-scrolling",
      "operative": "^0.3.2",
      "string": "^3.0.0"
    }
  }
}
```

and that results in

```js
err  Repo jspm:army-knife not found
```

Which leads me to ask myself "why is it looking for army-knife in the jspm registry when the registry property is set to npm?".

**Comment by guybedford** [comment]
Thanks for reporting this so clearly. I've fixed this up in https://github.com/jspm/jspm-cli/commit/8f97a85c0b25cdaf6bccf11dd9b0959aa0df4340.

**Comment by trusktr** [comment]
I'm still getting the same error with the second configuration. What does the `err  Unable to load endpoint army-knife@npm` mean exactly, anyway?

**Comment by trusktr** [comment]
And also still getting this error with the first configuration.

**Comment by guybedford** [comment]
I haven't released the change yet - it is fixed though.

**Comment by trusktr** [comment]
I `npm link`ed jspm from github@master when I tested, so that commit was there.

**Comment by guybedford** [comment]
The second configuration won't work here - just the first.

**Comment by trusktr** [comment]
Yeah, makes sense after the comments in the other issues, but the first configuration still gives me the same error:

```
Configuration file jspm_config.js doesn't exist, create it?: Yes
ok   The app/* path has been set to lib/*.js.
     To alter this path, set the directories.lib in the package.json or run jspm init -p to set the code folder.

     Looking up npm:army-knife
     Looking up npm:async
     Looking up npm:infamous
     Looking up npm:james-bond
     Looking up npm:jss
     Looking up npm:jss-nested
     Looking up npm:operative
     Looking up npm:string
     Updating registry cache...
     Looking up github:MikeMcl/big.js
     Looking up github:trusktr/famous
     Looking up github:eternicode/bootstrap-datepicker
     Looking up github:MikeMcl/bignumber.js
     Looking up github:iamceege/tooltipster
     Looking up github:jonasraoni/JSFromHell
     Looking up github:RickMohr/Leaflet
     Downloading npm:jss-nested@0.1.6
     Downloading npm:army-knife@0.1.1
     Looking up npm:6to5
     Downloading npm:jss@1.0.3
     Looking up npm:css
     Looking up npm:commander

warn No main entry point detected for npm:infamous@0.0.34.
     Try adding an override, or set the package.json "main": false if this is the intention.


err  Endpoint not found.

err  Unable to load endpoint army-knife@npm

warn Installation changes not saved.
```

**Comment by trusktr** [comment]
Did I do something wrong in [army-knife](http://npmjs.org/package/army-knife)?

**Comment by guybedford** [comment]
The only issue in army-knife is that you have a jspm dependency on npm:6to5 unless you do `dependencies: {}` in the jspm property.

It is perhaps something else you're installing that has a dependency on army-knife of a strange form?

**Comment by trusktr** [comment]
Thanks, I added the empty dependencies to the jspm field, so now army-knife@0.2.1 is on npmjs, but I still get the same problem.

My project has army-knife listed as you see in the first example above, and infamous also has army-knife listed as `"army-knife": "npm:army-knife@^0.2.1",
`.

There's no other package depending on army-knife in my project. Just my project, and infamous.

**Comment by guybedford** [comment]
If I have a fresh project with:

```json
{
  "registry": "jspm",
  "dependencies": {
    "army-knife": "npm:army-knife"
  }
}
```
and do `jspm install` it works ok. So there must be something else that depends on army-knife incorrectly here?

**Comment by trusktr** [comment]
The only other thing depending on army-knife is infamous. I just tried your config, and it works, but then I tried

```
{
  "registry": "jspm",
  "dependencies": {
    "infamous": "npm:infamous"
  }
}
```

and it fails with that error! Have I done something wrong in [infamous](https://github.com/infamous/infamous)?

**Comment by trusktr** [comment]
infamous is using army-knife@^0.1.0, so it'd be getting army-knife 0.1.1. Do you see anything wrong with [army-knife@0.1.1](https://github.com/trusktr/army-knife/tree/v0.1.1)?

**Comment by guybedford** [comment]
Your issue is that infamous is still using `registry: npm`, see https://github.com/infamous/infamous/blob/v0.0.34/package.json#L43.

You need to explicitly install infamous@master if you want the `registry: jspm` change.

**Comment by trusktr** [comment]
Oh, right! You should aim to prevent people like me being confused by just having a single format in which dependencies are specified, as I just happened to mention at https://github.com/jspm/jspm-cli/issues/454#issuecomment-72392432.  I won't be the only one confused in the future, surely. :)

**Comment by trusktr** [comment]
Could you at least change the error message, perhaps something along the lines of

```
err  Invalid dependency name specified in package npm:infamous@0.0.34 using registry format npm.
```

Perhaps also add a link to the docs where this is explained, when that's ready, but at least that error would make some sense. The other one is totally unhelpful.

**Comment by trusktr** [comment]
Note, the keywords "name" and "format" hint at the problem.
